build:
  maxIssues: 50

style:
  active: true
  MaxLineLength:
    active: false
  MagicNumber:
    active: false
  WildcardImport:
    active: true
    excludeImports:
      - "java.util.*"
  NewLineAtEndOfFile:
    active: false
  UnusedPrivateMember:
    active: true

potential-bugs:
  active: true

performance:
  active: true

exceptions:
  active: true

comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: true
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

naming:
  active: true
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false
